seed: 0

encdec:
  - 1024
  - 512
  - &bn_layer 8 # should be the same!
  - 32
  - 512
clustering_layer:
  - *bn_layer # should be the same!
  - 1024

dataset_path: ??? # metabric_version1.pkl

batch_size: 360
stage_I_epochs: 100
stage_II_epochs: 150
stage_III_epochs: 1000

train_fusion_start_epochs: 500000 # fixed weights
apply_reliable_pseudo_labels: true
pseudo_labels_k: 50
train_with_pseudo_labels_shuffle: true
cosine_neighbor_threshold: 0.5 # in range [-1,1]

pseudo_cca_loss: true
ps_ce_loss_lambda: 1
ps_cca_loss_lambda: 1
n_cca_components: 8

logs_dir: logs

trainer:
  accelerator: gpu
  devices: [0]
  max_epochs: 400
  deterministic: true
  logger: true
  log_every_n_steps: 10
  check_val_every_n_epoch: 10
  enable_checkpointing: false
  sync_batchnorm: true
  num_sanity_val_steps: 0
  enable_progress_bar: true
